version: "3"

volumes:
  mongo-data:

services:
  nuxt:
    build: ./
    restart: always
    container_name: fairceptron-nuxt
    environment:
      - MONGO_DB_USER=mongoose
      - MONGO_DB_NAME=fairceptron
      - MONGO_AUTH_SOURCE=fairceptron
      - MONGO_DOMAIN=mongodb # name of the db service (docker network)
      - MONGO_PORT=27017
      # MONGO_DB_PASS needs to be set in .env
    ports:
      - "3000:3000"
    command:
      "yarn run start"

  mongodb:
    image: "mongo:4"
    container_name: fairceptron-mongodb
    env_file: .env
    environment:
      - MONGO_INITDB_DATABASE=fairceptron
      - MONGO_INITDB_ROOT_USERNAME=admin
      # MONGO_INITDB_ROOT_PASSWORD needs to be set in .env
    volumes:
      - ./init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh
      - mongo-data:/data/db
    ports:
      - '27017-27019:27017-27019'